services:
  - type: web
    name: student-rooms-backend
    env: go
    plan: free
    buildCommand: go build -o server ./cmd/server
    startCommand: ./server
    envVars:
      - key: SUPABASE_DB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
